<?php
declare(strict_types=1);

//extend the player class and extend it to a newly created dealer class.
class Dealer extends Player
{
    public function hit(Deck $deck):void
    {
        if ($this->getScore() < 15) {
            parent::hit($deck); // TODO: Change the autogenerated stub
        }
    }

}
